import os

from github import Github, GithubException

DEPLOY_YML = """name: Deploy to GCS
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCS_SA_KEY }}'
      - uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: index.html
          destination: bexo-portfolios/${{ github.event.repository.name }}/site
          headers: |-
            cache-control: public, max-age=300
      - name: Purge Cloudflare cache
        run: |
          curl -sS -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \\
            -H "Authorization: Bearer ${{ secrets.CF_TOKEN }}" \\
            -H "Content-Type: application/json" \\
            --data '{"purge_everything":true}'
"""


def _client() -> Github:
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        raise ValueError("GITHUB_TOKEN is required")
    return Github(token)


def _create_repo(owner, name: str, handle: str):
    try:
        return owner.get_repo(name)
    except GithubException:
        repo = owner.create_repo(
            name,
            description=f"Portfolio for @{handle} — generated by BEXO",
            private=False,
            auto_init=True,
        )
        try:
            repo.create_file(
                ".github/workflows/deploy.yml",
                "ci: add deploy workflow",
                DEPLOY_YML,
            )
        except GithubException:
            pass
        return repo


def get_or_create_repo(handle: str):
    g = _client()
    name = f"portfolio-{handle}"
    org_name = (os.environ.get("GITHUB_ORG") or "").strip()

    if org_name and org_name.lower() not in ("none", "user", "auto"):
        try:
            org = g.get_organization(org_name)
            return _create_repo(org, name, handle)
        except GithubException as e:
            if getattr(e, "status", None) != 404:
                raise
            print(f"[GITHUB] org '{org_name}' not found — using token user account")

    user = g.get_user()
    return _create_repo(user, name, handle)


def upsert(repo, path: str, content: str, msg: str) -> None:
    try:
        existing = repo.get_contents(path)
        repo.update_file(path, msg, content, existing.sha)
    except GithubException:
        repo.create_file(path, msg, content)


def push_to_github(handle: str, html: str, spec: str, profile_id: str) -> str:
    domain = os.environ.get("PORTFOLIO_DOMAIN", "mybexo.com")
    repo = get_or_create_repo(handle)
    upsert(repo, "index.html", html, f"build: portfolio for {handle}")
    upsert(repo, "portfolio.md", spec, "docs: portfolio spec")
    upsert(
        repo,
        "README.md",
        f"# {handle}'s Portfolio\n\nLive: https://{handle}.{domain}\nProfile ID: `{profile_id}`\n",
        "docs: readme",
    )
    return repo.html_url
